### ISSUE TITLE
New README

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [testwiz/testwiz.github.io#8]
A new readme is needed

**Comment by GalaxyGamingBoy** [comment]
@odysseuskir You are free to take this one

**Comment by odysseuskir** [comment]
Alr!

**Comment by GalaxyGamingBoy** [comment]
Issue assigned.
If you need help feel free to message me

**Comment by odysseuskir** [comment]
I know how to make a readme lol

**Comment by GalaxyGamingBoy** [comment]
It was just a placeholder message lol
